# TCL File Generated by Component Editor 24.1
# Sat May 03 14:05:03 CEST 2025
# DO NOT MODIFY


# 
# stream_counter "Stream Source Avalon Counter" v1.0
#  2025.05.03.14:05:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module stream_counter
# 
set_module_property DESCRIPTION ""
set_module_property NAME stream_counter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Stream Source Avalon Counter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL stream_counter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file stream_counter.sv SYSTEM_VERILOG PATH stream_IPS/stream_counter.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_W INTEGER 32
set_parameter_property DATA_W DEFAULT_VALUE 32
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W TYPE INTEGER
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_W HDL_PARAMETER true
add_parameter CLK_FREQ_HZ INTEGER 100000000
set_parameter_property CLK_FREQ_HZ DEFAULT_VALUE 100000000
set_parameter_property CLK_FREQ_HZ DISPLAY_NAME CLK_FREQ_HZ
set_parameter_property CLK_FREQ_HZ TYPE INTEGER
set_parameter_property CLK_FREQ_HZ UNITS None
set_parameter_property CLK_FREQ_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_FREQ_HZ HDL_PARAMETER true
add_parameter STREAM_RATE_HZ INTEGER 625000
set_parameter_property STREAM_RATE_HZ DEFAULT_VALUE 625000
set_parameter_property STREAM_RATE_HZ DISPLAY_NAME STREAM_RATE_HZ
set_parameter_property STREAM_RATE_HZ TYPE INTEGER
set_parameter_property STREAM_RATE_HZ UNITS None
set_parameter_property STREAM_RATE_HZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property STREAM_RATE_HZ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source stream_tdata data Output "((DATA_W-1)) - (0) + 1"
add_interface_port avalon_streaming_source stream_tvalid valid Output 1
add_interface_port avalon_streaming_source stream_tready ready Input 1
add_interface_port avalon_streaming_source stream_tstart startofpacket Output 1
add_interface_port avalon_streaming_source stream_tlast endofpacket Output 1

